USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- INSIGHT 1: All-time highest and lowest gold close price

SELECT
  'GOLD' AS COMMODITY,
  MAX(CLOSE_PRICE) AS ALL_TIME_HIGH,
  MIN(CLOSE_PRICE) AS ALL_TIME_LOW,
  ROUND(AVG(CLOSE_PRICE), 2) AS AVG_PRICE,
  ROUND(STDDEV(CLOSE_PRICE), 2) AS PRICE_STDDEV
FROM ANALYTICS.FACT_GOLD_MARKET;



-- INSIGHT 2: All-time highest and lowest oil close price

SELECT
  'OIL' AS COMMODITY,
  MAX(CLOSE_PRICE) AS ALL_TIME_HIGH,
  MIN(CLOSE_PRICE) AS ALL_TIME_LOW,
  ROUND(AVG(CLOSE_PRICE), 2) AS AVG_PRICE,
  ROUND(STDDEV(CLOSE_PRICE), 2) AS PRICE_STDDEV
FROM ANALYTICS.FACT_OIL_MARKET;


-- INSIGHT 3: Dates of extreme gold price events

SELECT TRADE_DATE, CLOSE_PRICE, 'ALL-TIME HIGH' AS EVENT_TYPE
FROM ANALYTICS.FACT_GOLD_MARKET
WHERE CLOSE_PRICE = (SELECT MAX(CLOSE_PRICE) FROM ANALYTICS.FACT_GOLD_MARKET)
UNION ALL
SELECT TRADE_DATE, CLOSE_PRICE, 'ALL-TIME LOW'
FROM ANALYTICS.FACT_GOLD_MARKET
WHERE CLOSE_PRICE = (SELECT MIN(CLOSE_PRICE) FROM ANALYTICS.FACT_GOLD_MARKET);

-- INSIGHT 4: Annual average gold vs oil price comparison

SELECT
  g.YEAR,
  ROUND(AVG(g.CLOSE_PRICE), 2) AS AVG_GOLD_PRICE,
  ROUND(AVG(o.CLOSE_PRICE), 2) AS AVG_OIL_PRICE,
  ROUND(AVG(g.TRADE_VOLUME), 0) AS AVG_GOLD_VOLUME,
  ROUND(AVG(o.TRADE_VOLUME), 0) AS AVG_OIL_VOLUME
FROM ANALYTICS.FACT_GOLD_MARKET g
LEFT JOIN ANALYTICS.FACT_OIL_MARKET o ON g.TRADE_DATE = o.TRADE_DATE
GROUP BY g.YEAR
ORDER BY g.YEAR;

-- INSIGHT 5: Top 10 highest-volume trading days for gold

SELECT
  TRADE_DATE,
  YEAR,
  CLOSE_PRICE,
  TRADE_VOLUME,
  ROUND((TRADE_VOLUME - AVG(TRADE_VOLUME) OVER ()) / NULLIF(STDDEV(TRADE_VOLUME) OVER (), 0), 2) AS VOLUME_ZSCORE,
  PCT_CHANGE
FROM ANALYTICS.FACT_GOLD_MARKET
QUALIFY VOLUME_ZSCORE > 2
ORDER BY TRADE_VOLUME DESC
LIMIT 10;


-- INSIGHT 6: Top 10 highest-volume trading days for oil

SELECT *
FROM (
  SELECT
    TRADE_DATE,
    YEAR,
    CLOSE_PRICE,
    TRADE_VOLUME,
    ROUND((TRADE_VOLUME - AVG(TRADE_VOLUME) OVER ()) / NULLIF(STDDEV(TRADE_VOLUME) OVER (), 0), 2) AS VOLUME_ZSCORE,
    PCT_CHANGE
  FROM ANALYTICS.FACT_OIL_MARKET
)
WHERE VOLUME_ZSCORE > 2
ORDER BY TRADE_VOLUME DESC
LIMIT 10;

-- The TRADE_VOLUME field is entirely NULL for all 22 oil market records; therefore, the top 10 highest-volume oil trading days cannot be determined due to insufficient data.

-- INSIGHT 7: Monthly average gold prices or trend analysis

SELECT
  YEAR_MONTH,
  YEAR,
  MONTH_NAME,
  ROUND(AVG(CLOSE_PRICE), 2)  AS AVG_CLOSE,
  ROUND(MAX(CLOSE_PRICE), 2)  AS MONTH_HIGH,
  ROUND(MIN(CLOSE_PRICE), 2)  AS MONTH_LOW,
  ROUND(AVG(TRADE_VOLUME), 0) AS AVG_VOLUME
FROM ANALYTICS.FACT_GOLD_MARKET
GROUP BY YEAR_MONTH, YEAR, MONTH_NAME
ORDER BY YEAR_MONTH;

-- INSIGHT 8: Oil price crash analysis (2014-2016)

SELECT
  YEAR_QUARTER,
  ROUND(AVG(CLOSE_PRICE), 2) AS AVG_OIL_PRICE,
  ROUND(MIN(CLOSE_PRICE), 2) AS MIN_PRICE,
  ROUND(MAX(CLOSE_PRICE), 2) AS MAX_PRICE,
  COUNT(*) AS TRADING_DAYS
FROM ANALYTICS.FACT_OIL_MARKET
WHERE YEAR BETWEEN 2014 AND 2016
GROUP BY YEAR_QUARTER
ORDER BY YEAR_QUARTER;

-- INSIGHT 9: Gold year-to-date return by year

SELECT
  YEAR,
  YEAR_OPEN,
  YEAR_CLOSE,
  YTD_RETURN_PCT
FROM (
  SELECT
    YEAR,
    FIRST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE) AS YEAR_OPEN,
    LAST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS YEAR_CLOSE,
    ROUND((LAST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
      - FIRST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE))
      / NULLIF(FIRST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE), 0) * 100, 2) AS YTD_RETURN_PCT,
    ROW_NUMBER() OVER (PARTITION BY YEAR ORDER BY TRADE_DATE DESC) AS RN
  FROM ANALYTICS.FACT_GOLD_MARKET
)
WHERE RN = 1
ORDER BY YEAR;


-- INSIGHT 10: Largest single-day gold price moves (volatility events)

SELECT
  TRADE_DATE,
  CLOSE_PRICE,
  PREV_DAY_CLOSE,
  DOD_CHANGE,
  PCT_CHANGE
FROM ANALYTICS.FACT_GOLD_MARKET
WHERE ABS(PCT_CHANGE) > 2         -- moves > 2% in a day are significant
ORDER BY ABS(PCT_CHANGE) DESC
LIMIT 15;



