USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;


--  Audit log table

CREATE OR REPLACE TABLE AUDIT.DQ_LOG (
  CHECK_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
  RUN_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  TABLE_NAME      VARCHAR(100),
  CHECK_NAME      VARCHAR(200),
  ISSUE_COUNT     NUMBER,
  TOTAL_ROWS      NUMBER,
  PCT_AFFECTED    FLOAT,
  SEVERITY        VARCHAR(10),   -- HIGH / MEDIUM / LOW
  NOTES           VARCHAR(500)
);

-- Gold data quality checks

-- Total rows 

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'TOTAL_ROW_COUNT',
  0,
  COUNT(*),
  0,
  'LOW',
  'Baseline row count on load'
FROM RAW.RAW_GOLD_MARKET_DATA;

-- NULL / Blank dates

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'NULL_OR_BLANK_DATE',
  SUM(CASE WHEN "DATE" IS NULL OR TRIM("DATE") = '' THEN 1 ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE WHEN "DATE" IS NULL OR TRIM("DATE") = '' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE WHEN "DATE" IS NULL OR TRIM("DATE") = '' THEN 1 ELSE 0 END) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'Rows without a parseable date'
FROM RAW.RAW_GOLD_MARKET_DATA;

-- Duplicate dates

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
WITH DUP AS (
  SELECT DATE, COUNT(*) AS CNT
  FROM RAW.RAW_GOLD_MARKET_DATA
  GROUP BY DATE
  HAVING COUNT(*) > 1
)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'DUPLICATE_DATES',
  COALESCE(SUM(CNT - 1), 0),
  (SELECT COUNT(*) FROM RAW.RAW_GOLD_MARKET_DATA),
  ROUND(100.0 * COALESCE(SUM(CNT - 1), 0) / NULLIF((SELECT COUNT(*) FROM RAW.RAW_GOLD_MARKET_DATA), 0), 2),
  CASE WHEN COALESCE(SUM(CNT - 1), 0) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'Duplicate DATE values in gold dataset'
FROM DUP;

-- NULL numeric fields

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'NULL_PRICE_OR_VOLUME',
  SUM(CASE WHEN CLOSE IS NULL OR VOLUME IS NULL THEN 1 ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE WHEN CLOSE IS NULL OR VOLUME IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE WHEN CLOSE IS NULL OR VOLUME IS NULL THEN 1 ELSE 0 END) > 0 THEN 'MEDIUM' ELSE 'LOW' END,
  'Rows where CLOSE price or VOLUME is NULL after load'
FROM RAW.RAW_GOLD_MARKET_DATA;

-- Negative or zero CLOSE price (invalid)
INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'NON_POSITIVE_CLOSE_PRICE',
  SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'CLOSE price must be positive for market data'
FROM RAW.RAW_GOLD_MARKET_DATA;


-- OHLC logical check (LOW <= OPEN <= HIGH and LOW <= CLOSE <= HIGH)
INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_GOLD_MARKET_DATA',
  'OHLC_LOGIC_VIOLATION',
  SUM(CASE
        WHEN TRY_TO_DOUBLE(LOW)   > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  < TRY_TO_DOUBLE(LOW)   THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) < TRY_TO_DOUBLE(LOW)   THEN 1
        ELSE 0
      END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE
        WHEN TRY_TO_DOUBLE(LOW)   > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  < TRY_TO_DOUBLE(LOW)   THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) < TRY_TO_DOUBLE(LOW)   THEN 1
        ELSE 0
      END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE
        WHEN TRY_TO_DOUBLE(LOW) > TRY_TO_DOUBLE(HIGH) THEN 1
        ELSE 0 END) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'Low > High or Close outside Low-High range'
FROM RAW.RAW_GOLD_MARKET_DATA;

-- Oil data quality checks (using same pattern)

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT 'RAW_OIL_MARKET_DATA', 'TOTAL_ROW_COUNT', 0, COUNT(*), 0, 'LOW', 'Baseline row count on load'
FROM RAW.RAW_OIL_MARKET_DATA;

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_OIL_MARKET_DATA',
  'NULL_OR_BLANK_DATE',
  SUM(CASE WHEN DATE IS NULL OR TRIM(DATE) = '' THEN 1 ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE WHEN DATE IS NULL OR TRIM(DATE) = '' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE WHEN DATE IS NULL OR TRIM(DATE) = '' THEN 1 ELSE 0 END) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'Rows without a parseable date'
FROM RAW.RAW_OIL_MARKET_DATA;

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
WITH DUP AS (
  SELECT DATE, COUNT(*) AS CNT
  FROM RAW.RAW_OIL_MARKET_DATA
  GROUP BY DATE HAVING COUNT(*) > 1
)
SELECT
  'RAW_OIL_MARKET_DATA', 'DUPLICATE_DATES',
  COALESCE(SUM(CNT - 1), 0),
  (SELECT COUNT(*) FROM RAW.RAW_OIL_MARKET_DATA),
  ROUND(100.0 * COALESCE(SUM(CNT - 1), 0) / NULLIF((SELECT COUNT(*) FROM RAW.RAW_OIL_MARKET_DATA),0), 2),
  CASE WHEN COALESCE(SUM(CNT - 1), 0) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'Duplicate DATE values in oil dataset'
FROM DUP;

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_OIL_MARKET_DATA', 'NON_POSITIVE_CLOSE_PRICE',
  SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  CASE WHEN SUM(CASE WHEN TRY_TO_DOUBLE(CLOSE) <= 0 THEN 1 ELSE 0 END) > 0 THEN 'HIGH' ELSE 'LOW' END,
  'CLOSE price must be positive for market data'
FROM RAW.RAW_OIL_MARKET_DATA;

INSERT INTO AUDIT.DQ_LOG (TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY, NOTES)
SELECT
  'RAW_OIL_MARKET_DATA', 'OHLC_LOGIC_VIOLATION',
  SUM(CASE
        WHEN TRY_TO_DOUBLE(LOW)   > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(OPEN)  < TRY_TO_DOUBLE(LOW)   THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) > TRY_TO_DOUBLE(HIGH)  THEN 1
        WHEN TRY_TO_DOUBLE(CLOSE) < TRY_TO_DOUBLE(LOW)   THEN 1
        ELSE 0 END),
  COUNT(*),
  ROUND(100.0 * SUM(CASE
        WHEN TRY_TO_DOUBLE(LOW)   > TRY_TO_DOUBLE(HIGH)  THEN 1
        ELSE 0 END) / NULLIF(COUNT(*),0), 2),
  'LOW',
  'OHLC logic check for oil prices'
FROM RAW.RAW_OIL_MARKET_DATA;

-- Data Quality Summary

SELECT TABLE_NAME, CHECK_NAME, ISSUE_COUNT, TOTAL_ROWS, PCT_AFFECTED, SEVERITY
FROM AUDIT.DQ_LOG
ORDER BY RUN_TS, TABLE_NAME, CHECK_NAME;

