USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

COPY INTO RAW.RAW_GOLD_MARKET_DATA (
  DATE, OPEN, HIGH, LOW, CLOSE, VOLUME,
  SP500, DOW_JONES, USD_INDEX, GOLD_ETF, OIL_ETF,
  _FILE_NAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    METADATA$FILENAME
  FROM @RAW.COMMODITY_STAGE/gold_stocks_price.csv
)
FILE_FORMAT    = (FORMAT_NAME = 'RAW.CSV_FORMAT')
ON_ERROR       = 'CONTINUE'
PURGE          = FALSE;

COPY INTO RAW.RAW_OIL_MARKET_DATA (
  DATE, OPEN, HIGH, LOW, CLOSE, VOLUME,
  _FILE_NAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6,
    METADATA$FILENAME
  FROM @RAW.COMMODITY_STAGE/oil_price.csv
)
FILE_FORMAT    = (FORMAT_NAME = 'RAW.CSV_FORMAT')
ON_ERROR       = 'CONTINUE'
PURGE          = FALSE;

---- Verify load counts

SELECT 'RAW_GOLD_MARKET_DATA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.RAW_GOLD_MARKET_DATA
UNION ALL
SELECT 'RAW_OIL_MARKET_DATA', COUNT(*) FROM RAW.RAW_OIL_MARKET_DATA;

