USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- View 1: Gold market summary by year

CREATE OR REPLACE VIEW ANALYTICS.VW_GOLD_ANNUAL_SUMMARY AS
WITH yearly_bounds AS (
  SELECT
    YEAR,
    FIRST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE) AS YEAR_OPEN,
    LAST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS YEAR_CLOSE,
    CLOSE_PRICE,
    TRADE_VOLUME,
    TRADE_DATE
  FROM ANALYTICS.FACT_GOLD_MARKET
)
SELECT
  YEAR,
  COUNT(*) AS TRADING_DAYS,
  ROUND(MIN(CLOSE_PRICE), 2) AS YEAR_LOW,
  ROUND(MAX(CLOSE_PRICE), 2) AS YEAR_HIGH,
  ROUND(AVG(CLOSE_PRICE), 2) AS YEAR_AVG,
  ROUND(SUM(TRADE_VOLUME), 0) AS TOTAL_VOLUME,
  ROUND((MAX(YEAR_CLOSE) - MAX(YEAR_OPEN)) / NULLIF(MAX(YEAR_OPEN), 0) * 100, 2) AS ANNUAL_RETURN_PCT
FROM yearly_bounds
GROUP BY YEAR
ORDER BY YEAR;

-- View 2: Oil market summary by year

CREATE OR REPLACE VIEW ANALYTICS.VW_OIL_ANNUAL_SUMMARY AS
WITH yearly_bounds AS (
  SELECT
    YEAR,
    FIRST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE) AS YEAR_OPEN,
    LAST_VALUE(CLOSE_PRICE) OVER (PARTITION BY YEAR ORDER BY TRADE_DATE
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS YEAR_CLOSE,
    CLOSE_PRICE,
    TRADE_VOLUME,
    TRADE_DATE
  FROM ANALYTICS.FACT_OIL_MARKET
)
SELECT
  YEAR,
  COUNT(*) AS TRADING_DAYS,
  ROUND(MIN(CLOSE_PRICE), 2) AS YEAR_LOW,
  ROUND(MAX(CLOSE_PRICE), 2) AS YEAR_HIGH,
  ROUND(AVG(CLOSE_PRICE), 2) AS YEAR_AVG,
  ROUND(SUM(TRADE_VOLUME), 0) AS TOTAL_VOLUME,
  ROUND((MAX(YEAR_CLOSE) - MAX(YEAR_OPEN)) / NULLIF(MAX(YEAR_OPEN), 0) * 100, 2) AS ANNUAL_RETURN_PCT
FROM yearly_bounds
GROUP BY YEAR
ORDER BY YEAR;

-- View 3: Gold volume anomaly events

CREATE OR REPLACE VIEW ANALYTICS.VW_GOLD_VOLUME_ANOMALIES AS
SELECT
  TRADE_DATE,
  YEAR,
  CLOSE_PRICE,
  TRADE_VOLUME,
  VOLUME_ZSCORE,
  CASE
    WHEN VOLUME_ZSCORE > 2 THEN 'HIGH_VOLUME_EVENT'
    WHEN VOLUME_ZSCORE < -2 THEN 'LOW_VOLUME_EVENT'
    ELSE 'NORMAL'
  END AS VOLUME_FLAG,
  PCT_CHANGE
FROM (
  SELECT
    TRADE_DATE,
    YEAR,
    CLOSE_PRICE,
    TRADE_VOLUME,
    ROUND((TRADE_VOLUME - AVG(TRADE_VOLUME) OVER ()) / NULLIF(STDDEV(TRADE_VOLUME) OVER (), 0), 2) AS VOLUME_ZSCORE,
    PCT_CHANGE
  FROM ANALYTICS.FACT_GOLD_MARKET
)
WHERE ABS(VOLUME_ZSCORE) > 2;


-- View 4 : VW_DAILY_COMMODITY_COMBINED

CREATE OR REPLACE VIEW ANALYTICS.VW_DAILY_COMMODITY_COMBINED AS
SELECT
    g.TRADE_DATE,
    g.YEAR,
    g.YEAR_MONTH,
    g.CLOSE_PRICE   AS GOLD_CLOSE,
    o.CLOSE_PRICE   AS OIL_CLOSE,
    g.MA30_CLOSE    AS GOLD_MA30,
    o.MA30_CLOSE    AS OIL_MA30,
    g.PCT_CHANGE    AS GOLD_PCT_CHANGE,
    o.PCT_CHANGE    AS OIL_PCT_CHANGE,
    ROUND(g.CLOSE_PRICE / NULLIF(o.CLOSE_PRICE, 0), 2) AS GOLD_OIL_RATIO
FROM ANALYTICS.FACT_GOLD_MARKET g
LEFT JOIN ANALYTICS.FACT_OIL_MARKET o
       ON g.TRADE_DATE = o.TRADE_DATE;