USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- HYPOTHESIS 1
-- "Oil is structurally more volatile than gold and is therefore a
--  riskier holding for a treasury portfolio."
-- Test: compare annualised volatility (stdev of daily returns * sqrt(252)).

WITH gold_ret AS (
    SELECT TRADE_DATE, PCT_CHANGE AS RET FROM ANALYTICS.FACT_GOLD_MARKET WHERE PCT_CHANGE IS NOT NULL
),
oil_ret AS (
    SELECT TRADE_DATE, PCT_CHANGE AS RET FROM ANALYTICS.FACT_OIL_MARKET WHERE PCT_CHANGE IS NOT NULL
)
SELECT
    'GOLD' AS COMMODITY,
    ROUND(STDDEV(RET), 3)                  AS DAILY_VOL_PCT,
    ROUND(STDDEV(RET) * SQRT(252), 1)      AS ANNUALISED_VOL_PCT
FROM gold_ret
UNION ALL
SELECT
    'OIL',
    ROUND(STDDEV(RET), 3),
    ROUND(STDDEV(RET) * SQRT(252), 1)
FROM oil_ret;

-- HYPOTHESIS 2
-- "A strong US dollar pushes gold prices down (the classic inverse link)."
-- Test: correlation of gold close price level against the USD Index level.

SELECT
    ROUND(CORR(CLOSE_PRICE, USD_INDEX), 3) AS GOLD_USD_LEVEL_CORR,
    CASE
        WHEN CORR(CLOSE_PRICE, USD_INDEX) < -0.5 THEN 'STRONG INVERSE - hypothesis supported'
        WHEN CORR(CLOSE_PRICE, USD_INDEX) <  0   THEN 'MILD INVERSE'
        ELSE 'NO INVERSE RELATIONSHIP'
    END AS VERDICT
FROM ANALYTICS.FACT_GOLD_MARKET
WHERE USD_INDEX IS NOT NULL;

-- HYPOTHESIS 3
-- "Gold acts as a safe haven: on the worst equity (S&P 500) days, gold
--  rises while stocks fall."

WITH sp_daily AS (
    SELECT
        TRADE_DATE,
        PCT_CHANGE AS GOLD_RET,
        (SP500_INDEX - LAG(SP500_INDEX) OVER (ORDER BY TRADE_DATE))
            / NULLIF(LAG(SP500_INDEX) OVER (ORDER BY TRADE_DATE), 0) * 100 AS SP_RET
    FROM ANALYTICS.FACT_GOLD_MARKET
    WHERE SP500_INDEX IS NOT NULL
),
worst_sp AS (
    SELECT GOLD_RET, SP_RET
    FROM sp_daily
    WHERE SP_RET IS NOT NULL
    QUALIFY SP_RET <= PERCENTILE_CONT(0.05) WITHIN GROUP (ORDER BY SP_RET) OVER ()
)
SELECT
    COUNT(*)                       AS WORST_SP_DAYS,
    ROUND(AVG(SP_RET), 2)          AS AVG_SP_RETURN_PCT,
    ROUND(AVG(GOLD_RET), 3)        AS AVG_GOLD_RETURN_PCT,
    CASE WHEN AVG(GOLD_RET) > 0 THEN 'SAFE HAVEN BEHAVIOUR CONFIRMED'
         ELSE 'NO SAFE-HAVEN EFFECT' END AS VERDICT
FROM worst_sp;

-- HYPOTHESIS 4
-- "Gold and oil move together, so holding both gives little
--  diversification benefit."

WITH joined AS (
    SELECT g.TRADE_DATE, g.YEAR, g.CLOSE_PRICE AS GOLD, o.CLOSE_PRICE AS OIL
    FROM ANALYTICS.FACT_GOLD_MARKET g
    JOIN ANALYTICS.FACT_OIL_MARKET o ON g.TRADE_DATE = o.TRADE_DATE
)
SELECT
    CASE
        WHEN YEAR BETWEEN 2011 AND 2013 THEN '2011-2013 Pre-crash'
        WHEN YEAR BETWEEN 2014 AND 2016 THEN '2014-2016 Oil crash'
        ELSE '2017-2018 Recovery'
    END AS REGIME,
    COUNT(*)                    AS PAIRED_DAYS,
    ROUND(CORR(GOLD, OIL), 3)   AS GOLD_OIL_CORR
FROM joined
GROUP BY REGIME
ORDER BY REGIME;

-- HYPOTHESIS 5
-- "High trading volume signals big price moves - volume is an early
--  warning indicator."

WITH base AS (
    SELECT TRADE_VOLUME, ABS(PCT_CHANGE) AS ABS_MOVE
    FROM ANALYTICS.FACT_GOLD_MARKET
    WHERE TRADE_VOLUME IS NOT NULL AND PCT_CHANGE IS NOT NULL
),
flagged AS (
    SELECT ABS_MOVE,
           CASE WHEN TRADE_VOLUME >= PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TRADE_VOLUME) OVER ()
                THEN 'TOP_5PCT_VOLUME' ELSE 'NORMAL' END AS VOL_BUCKET
    FROM base
)
SELECT
    VOL_BUCKET,
    COUNT(*)                  AS DAYS,
    ROUND(AVG(ABS_MOVE), 3)   AS AVG_ABS_MOVE_PCT
FROM flagged
GROUP BY VOL_BUCKET
ORDER BY VOL_BUCKET;

-- HYPOTHESIS 6
-- "Volatility clusters - turbulent days tend to follow turbulent days
--  (so risk is persistent, not random)."

WITH r AS (
    SELECT TRADE_DATE,
           ABS(PCT_CHANGE) AS ABS_RET,
           LAG(ABS(PCT_CHANGE)) OVER (ORDER BY TRADE_DATE) AS PREV_ABS_RET
    FROM ANALYTICS.FACT_OIL_MARKET
    WHERE PCT_CHANGE IS NOT NULL
)
SELECT
    ROUND(CORR(ABS_RET, PREV_ABS_RET), 3) AS VOL_AUTOCORR_LAG1,
    CASE WHEN CORR(ABS_RET, PREV_ABS_RET) > 0.2 THEN 'VOLATILITY CLUSTERS - risk is persistent'
         WHEN CORR(ABS_RET, PREV_ABS_RET) > 0.1 THEN 'MILD CLUSTERING'
         ELSE 'NO CLUSTERING' END AS VERDICT
FROM r WHERE PREV_ABS_RET IS NOT NULL;

-- HYPOTHESIS 7
-- "Extreme single-day moves (>2%) are rare for both commodities."

SELECT 'GOLD' AS COMMODITY,
       COUNT(*) AS TOTAL_DAYS,
       SUM(CASE WHEN ABS(PCT_CHANGE) > 2 THEN 1 ELSE 0 END) AS BIG_MOVE_DAYS,
       ROUND(100.0 * SUM(CASE WHEN ABS(PCT_CHANGE) > 2 THEN 1 ELSE 0 END) / COUNT(*), 1) AS PCT_BIG_DAYS
FROM ANALYTICS.FACT_GOLD_MARKET WHERE PCT_CHANGE IS NOT NULL
UNION ALL
SELECT 'OIL',
       COUNT(*),
       SUM(CASE WHEN ABS(PCT_CHANGE) > 2 THEN 1 ELSE 0 END),
       ROUND(100.0 * SUM(CASE WHEN ABS(PCT_CHANGE) > 2 THEN 1 ELSE 0 END) / COUNT(*), 1)
FROM ANALYTICS.FACT_OIL_MARKET WHERE PCT_CHANGE IS NOT NULL;

-- HYPOTHESIS 8
-- "Oil's drawdown risk is far worse than gold's - a long-only oil
--  position can lose more than half its value."

WITH dd AS (
    SELECT 'GOLD' AS COMMODITY, TRADE_DATE, CLOSE_PRICE,
           MAX(CLOSE_PRICE) OVER (ORDER BY TRADE_DATE ROWS UNBOUNDED PRECEDING) AS PEAK
    FROM ANALYTICS.FACT_GOLD_MARKET
    UNION ALL
    SELECT 'OIL', TRADE_DATE, CLOSE_PRICE,
           MAX(CLOSE_PRICE) OVER (ORDER BY TRADE_DATE ROWS UNBOUNDED PRECEDING)
    FROM ANALYTICS.FACT_OIL_MARKET
)
SELECT COMMODITY,
       ROUND(MIN((CLOSE_PRICE - PEAK) / NULLIF(PEAK,0) * 100), 1) AS MAX_DRAWDOWN_PCT
FROM dd
GROUP BY COMMODITY;

-- INSIGHT VIEW: persist the annual volatility comparison for dashboard

CREATE OR REPLACE VIEW ANALYTICS.VW_ANNUAL_VOLATILITY AS
SELECT YEAR, 'GOLD' AS COMMODITY,
       ROUND(STDDEV(PCT_CHANGE), 3) AS DAILY_VOL_PCT,
       ROUND(STDDEV(PCT_CHANGE) * SQRT(252), 1) AS ANNUALISED_VOL_PCT,
       COUNT(*) AS TRADING_DAYS
FROM ANALYTICS.FACT_GOLD_MARKET WHERE PCT_CHANGE IS NOT NULL GROUP BY YEAR
UNION ALL
SELECT YEAR, 'OIL',
       ROUND(STDDEV(PCT_CHANGE), 3),
       ROUND(STDDEV(PCT_CHANGE) * SQRT(252), 1),
       COUNT(*)
FROM ANALYTICS.FACT_OIL_MARKET WHERE PCT_CHANGE IS NOT NULL GROUP BY YEAR
ORDER BY YEAR, COMMODITY;

-- INSIGHT VIEW: regime-based gold-oil correlation for dashboards

CREATE OR REPLACE VIEW ANALYTICS.VW_REGIME_CORRELATION AS
WITH joined AS (
    SELECT g.TRADE_DATE, g.YEAR, g.CLOSE_PRICE AS GOLD, o.CLOSE_PRICE AS OIL
    FROM ANALYTICS.FACT_GOLD_MARKET g
    JOIN ANALYTICS.FACT_OIL_MARKET o ON g.TRADE_DATE = o.TRADE_DATE
)
SELECT
    CASE
        WHEN YEAR BETWEEN 2011 AND 2013 THEN '2011-2013 Pre-crash'
        WHEN YEAR BETWEEN 2014 AND 2016 THEN '2014-2016 Oil crash'
        ELSE '2017-2018 Recovery'
    END AS MARKET_REGIME,
    COUNT(*)                  AS PAIRED_DAYS,
    ROUND(CORR(GOLD, OIL), 3) AS GOLD_OIL_CORRELATION
FROM joined
GROUP BY MARKET_REGIME;

