USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- for safer alter/suspend task

ALTER TASK IF EXISTS STAGING.TASK_REFRESH_GOLD_STAGING SUSPEND;

-- first detect newly inserted rows at raw stage

CREATE OR REPLACE STREAM RAW.GOLD_RAW_STREAM
    ON TABLE RAW.RAW_GOLD_MARKET_DATA APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM RAW.OIL_RAW_STREAM
    ON TABLE RAW.RAW_OIL_MARKET_DATA  APPEND_ONLY = TRUE;

-- root task clean and load data to the actual task

CREATE OR REPLACE TASK STAGING.TASK_REFRESH_GOLD
    WAREHOUSE = COMMODITY_WH
    SCHEDULE  = '60 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.GOLD_RAW_STREAM')
AS
    INSERT INTO STAGING.STG_GOLD_MARKET
    SELECT
        TRY_TO_DATE(DATE),
        TRY_TO_DOUBLE(OPEN),
        TRY_TO_DOUBLE(HIGH),
        TRY_TO_DOUBLE(LOW),
        TRY_TO_DOUBLE(CLOSE),
        TRY_TO_NUMBER(REPLACE(VOLUME, ',', '')),
        TRY_TO_DOUBLE(SP500),
        TRY_TO_DOUBLE(DOW_JONES),
        TRY_TO_DOUBLE(USD_INDEX),
        TRY_TO_DOUBLE(GOLD_ETF),
        TRY_TO_DOUBLE(OIL_ETF),
        _LOADED_AT,
        _FILE_NAME
    FROM RAW.GOLD_RAW_STREAM
    WHERE TRY_TO_DATE(DATE) IS NOT NULL
      AND TRY_TO_DOUBLE(CLOSE) > 0
      AND TRY_TO_DOUBLE(LOW) <= TRY_TO_DOUBLE(HIGH);

-- child task rebuild after staging

CREATE OR REPLACE TASK STAGING.TASK_REBUILD_GOLD_FACT
    WAREHOUSE = COMMODITY_WH
    AFTER STAGING.TASK_REFRESH_GOLD
AS
    CREATE OR REPLACE TABLE ANALYTICS.FACT_GOLD_MARKET AS
    SELECT
        g.TRADE_DATE,
        d.YEAR,
        d.QUARTER,
        d.MONTH,
        d.MONTH_NAME,
        d.YEAR_QUARTER,
        d.YEAR_MONTH,
        d.IS_WEEKDAY,

        g.OPEN_PRICE,
        g.HIGH_PRICE,
        g.LOW_PRICE,
        g.CLOSE_PRICE,
        g.TRADE_VOLUME,
        ROUND(g.HIGH_PRICE - g.LOW_PRICE, 2) AS DAILY_RANGE,
        ROUND((g.CLOSE_PRICE - g.OPEN_PRICE) / NULLIF(g.OPEN_PRICE, 0) * 100, 4) AS PCT_CHANGE,

        g.SP500_INDEX,
        g.DOW_JONES_INDEX,
        g.USD_INDEX,
        g.GOLD_ETF_PRICE,
        g.OIL_ETF_PRICE,

        AVG(g.CLOSE_PRICE) OVER (ORDER BY g.TRADE_DATE
            ROWS BETWEEN 6  PRECEDING AND CURRENT ROW) AS MA7_CLOSE,
        AVG(g.CLOSE_PRICE) OVER (ORDER BY g.TRADE_DATE
            ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS MA30_CLOSE,
        AVG(g.CLOSE_PRICE) OVER (ORDER BY g.TRADE_DATE
            ROWS BETWEEN 89 PRECEDING AND CURRENT ROW) AS MA90_CLOSE,

        LAG(g.CLOSE_PRICE, 1) OVER (ORDER BY g.TRADE_DATE) AS PREV_DAY_CLOSE,
        g.CLOSE_PRICE - LAG(g.CLOSE_PRICE, 1) OVER (ORDER BY g.TRADE_DATE) AS DOD_CHANGE,

        STDDEV(g.CLOSE_PRICE) OVER (ORDER BY g.TRADE_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS VOLATILITY_7D
    FROM STAGING.STG_GOLD_MARKET g
    LEFT JOIN ANALYTICS.DIM_DATE d
        ON g.TRADE_DATE = d.CALENDAR_DATE;

-- data quality task runs after fact rebuild (must be in same schema as predecessor)

CREATE OR REPLACE TASK STAGING.TASK_RUN_DQ
    WAREHOUSE = COMMODITY_WH
    AFTER STAGING.TASK_REBUILD_GOLD_FACT
AS
    CALL AUDIT.SP_RUN_DQ_CHECKS();

-- resume tasks bottom-up (children first, then root)

ALTER TASK STAGING.TASK_RUN_DQ RESUME;
ALTER TASK STAGING.TASK_REBUILD_GOLD_FACT RESUME;
ALTER TASK STAGING.TASK_REFRESH_GOLD RESUME

-- vertification of pipeline is live

SHOW TASKS IN DATABASE COMMODITY_MARKET_PLATFORM;

SELECT name, state, scheduled_time, completed_time, error_message
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY scheduled_time DESC
LIMIT 20;
