USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- Quarterly gold price summary

SELECT YEAR_QUARTER, ROUND(AVG(CLOSE_PRICE),2) AS AVG_GOLD_PRICE
FROM ANALYTICS.FACT_GOLD_MARKET
GROUP BY YEAR_QUARTER ORDER BY YEAR_QUARTER;

-- Quarterly oil price summary

SELECT YEAR_QUARTER, ROUND(AVG(CLOSE_PRICE),2) AS AVG_OIL_PRICE
FROM ANALYTICS.FACT_OIL_MARKET
GROUP BY YEAR_QUARTER ORDER BY YEAR_QUARTER;

-- Combined annual view for exec report

SELECT * FROM ANALYTICS.VW_GOLD_ANNUAL_SUMMARY ORDER BY YEAR;
SELECT * FROM ANALYTICS.VW_OIL_ANNUAL_SUMMARY  ORDER BY YEAR;

-- Combined daily view (last 90 rows for trend chart)

SELECT * FROM ANALYTICS.VW_DAILY_COMMODITY_COMBINED
ORDER BY TRADE_DATE DESC LIMIT 90;
