
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMMODITY_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for Commodity Market Intelligence Platform';

USE WAREHOUSE COMMODITY_WH;

CREATE DATABASE IF NOT EXISTS COMMODITY_MARKET_PLATFORM;

USE DATABASE COMMODITY_MARKET_PLATFORM;

--layered schemas

CREATE SCHEMA IF NOT EXISTS RAW;            -- raw ingested data
CREATE SCHEMA IF NOT EXISTS STAGING;        -- cleaned staged data
CREATE SCHEMA IF NOT EXISTS ANALYTICS;      -- statistical table business ready
CREATE SCHEMA IF NOT EXISTS AUDIT;          -- data quality logs

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE             = 'CSV'
    FIELD_DELIMITER  = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER      = 1
    NULL_IF          = ('NULL', 'null', 'N/A', 'n/a', '', 'NaN')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE       = TRUE
    DATE_FORMAT      = 'AUTO';

CREATE OR REPLACE STAGE RAW.COMMODITY_STAGE
    FILE_FORMAT = RAW.CSV_FORMAT;

--gold_price_schema for RAW 

CREATE OR REPLACE TABLE RAW.RAW_GOLD_MARKET_DATA (
  DATE          VARCHAR(20),
  OPEN          VARCHAR(20),
  HIGH          VARCHAR(20),
  LOW           VARCHAR(20),
  CLOSE         VARCHAR(20),
  VOLUME        VARCHAR(30),
  SP500         VARCHAR(20),
  DOW_JONES     VARCHAR(20),
  USD_INDEX     VARCHAR(20),
  GOLD_ETF      VARCHAR(20),
  OIL_ETF       VARCHAR(20),
  _LOADED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _FILE_NAME    VARCHAR(256)
);

-- oil_price schema

CREATE OR REPLACE TABLE RAW.RAW_OIL_MARKET_DATA (
  DATE          VARCHAR(20),
  OPEN          VARCHAR(20),
  HIGH          VARCHAR(20),
  LOW           VARCHAR(20),
  CLOSE         VARCHAR(20),
  VOLUME        VARCHAR(30),
  _LOADED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _FILE_NAME    VARCHAR(256)
);

