USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- Staging gold table after preprocessing

CREATE OR REPLACE TABLE STAGING.STG_GOLD_MARKET AS
WITH ranked AS (
  SELECT
    TRY_TO_DATE(DATE)           AS TRADE_DATE,
    TRY_TO_DOUBLE(OPEN)         AS OPEN_PRICE,
    TRY_TO_DOUBLE(HIGH)         AS HIGH_PRICE,
    TRY_TO_DOUBLE(LOW)          AS LOW_PRICE,
    TRY_TO_DOUBLE(CLOSE)        AS CLOSE_PRICE,
    TRY_TO_NUMBER(REPLACE(VOLUME, ',', '')) AS TRADE_VOLUME,
    TRY_TO_DOUBLE(SP500)        AS SP500_INDEX,
    TRY_TO_DOUBLE(DOW_JONES)    AS DOW_JONES_INDEX,
    TRY_TO_DOUBLE(USD_INDEX)    AS USD_INDEX,
    TRY_TO_DOUBLE(GOLD_ETF)     AS GOLD_ETF_PRICE,
    TRY_TO_DOUBLE(OIL_ETF)      AS OIL_ETF_PRICE,
    _LOADED_AT,
    _FILE_NAME,
    ROW_NUMBER() OVER (
      PARTITION BY TRY_TO_DATE(DATE)
      ORDER BY _LOADED_AT DESC
    ) AS RN
  FROM RAW.RAW_GOLD_MARKET_DATA
  WHERE TRY_TO_DATE(DATE) IS NOT NULL           -- remove unparseable dates
    AND TRY_TO_DOUBLE(CLOSE) > 0                -- remove non-positive prices
    AND TRY_TO_DOUBLE(LOW)  <= TRY_TO_DOUBLE(HIGH) -- OHLC sanity
)
SELECT
  TRADE_DATE,
  OPEN_PRICE,
  HIGH_PRICE,
  LOW_PRICE,
  CLOSE_PRICE,
  TRADE_VOLUME,
  SP500_INDEX,
  DOW_JONES_INDEX,
  USD_INDEX,
  GOLD_ETF_PRICE,
  OIL_ETF_PRICE,
  _LOADED_AT,
  _FILE_NAME
FROM ranked
WHERE RN = 1;

-- Staging oil table after preprocessing

CREATE OR REPLACE TABLE STAGING.STG_OIL_MARKET AS
WITH ranked AS (
  SELECT
    TRY_TO_DATE("DATE")           AS TRADE_DATE,
    TRY_TO_DOUBLE(OPEN)           AS OPEN_PRICE,
    TRY_TO_DOUBLE(HIGH)           AS HIGH_PRICE,
    TRY_TO_DOUBLE(LOW)            AS LOW_PRICE,
    TRY_TO_DOUBLE(CLOSE)          AS CLOSE_PRICE,
    TRY_TO_NUMBER(REPLACE(VOLUME, ',', '')) AS TRADE_VOLUME,
    _LOADED_AT,
    _FILE_NAME,
    ROW_NUMBER() OVER (
      PARTITION BY TRY_TO_DATE("DATE")
      ORDER BY _LOADED_AT DESC
    ) AS RN
  FROM RAW.RAW_OIL_MARKET_DATA
  WHERE TRY_TO_DATE("DATE") IS NOT NULL
    AND TRY_TO_DOUBLE(CLOSE) > 0
    AND TRY_TO_DOUBLE(LOW) <= TRY_TO_DOUBLE(HIGH)
)
SELECT
  TRADE_DATE,
  OPEN_PRICE,
  HIGH_PRICE,
  LOW_PRICE,
  CLOSE_PRICE,
  TRADE_VOLUME,
  _LOADED_AT,
  _FILE_NAME
FROM ranked
WHERE RN = 1;

-- Verify staging row counts
SELECT
    'STG_GOLD_MARKET' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM STAGING.STG_GOLD_MARKET

UNION ALL

SELECT
    'STG_OIL_MARKET' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM STAGING.STG_OIL_MARKET;

