USE WAREHOUSE COMMODITY_WH;
USE DATABASE COMMODITY_MARKET_PLATFORM;

-- Row count across all layers

SELECT 'RAW' AS LAYER, 'GOLD' AS COMMODITY, COUNT(*) AS "ROWS" FROM RAW.RAW_GOLD_MARKET_DATA
UNION ALL SELECT 'STAGING', 'GOLD', COUNT(*) FROM STAGING.STG_GOLD_MARKET
UNION ALL SELECT 'ANALYTICS','GOLD', COUNT(*) FROM ANALYTICS.FACT_GOLD_MARKET
UNION ALL SELECT 'RAW',      'OIL',  COUNT(*) FROM RAW.RAW_OIL_MARKET_DATA
UNION ALL SELECT 'STAGING',  'OIL',  COUNT(*) FROM STAGING.STG_OIL_MARKET
UNION ALL SELECT 'ANALYTICS','OIL',  COUNT(*) FROM ANALYTICS.FACT_OIL_MARKET
ORDER BY COMMODITY, LAYER;

-- Date range check

SELECT 'GOLD' AS COMMODITY, MIN(TRADE_DATE) AS EARLIEST, MAX(TRADE_DATE) AS LATEST
FROM ANALYTICS.FACT_GOLD_MARKET
UNION ALL
SELECT 'OIL', MIN(TRADE_DATE), MAX(TRADE_DATE)
FROM ANALYTICS.FACT_OIL_MARKET;

-- Null check on critical analytics fields

SELECT
  COUNT(*) AS TOTAL_ROWS,
  SUM(CASE WHEN CLOSE_PRICE  IS NULL THEN 1 ELSE 0 END) AS NULL_CLOSE,
  SUM(CASE WHEN TRADE_DATE   IS NULL THEN 1 ELSE 0 END) AS NULL_DATE,
  SUM(CASE WHEN TRADE_VOLUME IS NULL THEN 1 ELSE 0 END) AS NULL_VOLUME,
  SUM(CASE WHEN MA7_CLOSE    IS NULL THEN 1 ELSE 0 END) AS NULL_MA7,
  SUM(CASE WHEN MA30_CLOSE   IS NULL THEN 1 ELSE 0 END) AS NULL_MA30
FROM ANALYTICS.FACT_GOLD_MARKET;
