CREATE WAREHOUSE IF NOT EXISTS INTEL_WH
WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS COMMODITY_INTEL;

CREATE SCHEMA   IF NOT EXISTS COMMODITY_INTEL.AUDIT;
CREATE SCHEMA   IF NOT EXISTS COMMODITY_INTEL.RAW;
CREATE SCHEMA   IF NOT EXISTS COMMODITY_INTEL.CLEAN;
CREATE SCHEMA   IF NOT EXISTS COMMODITY_INTEL.ANALYTICS;

USE WAREHOUSE INTEL_WH;
USE DATABASE  COMMODITY_INTEL;

CREATE TABLE IF NOT EXISTS AUDIT.RUN_LOG (
  run_id STRING, run_started TIMESTAMP_NTZ, step_no NUMBER, layer STRING,
  step_name STRING, object_name STRING, rows_in NUMBER, rows_out NUMBER,
  rows_dropped NUMBER, status STRING, message STRING,
  logged_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SET run_id      = (SELECT UUID_STRING());
SET run_started = (SELECT CURRENT_TIMESTAMP());

--overlap floor for cross-asset (DXY/VIX) analysis

SET overlap_floor = '2021-06-01'::DATE;

--for normal-approximation p-values.

CREATE OR REPLACE FUNCTION AUDIT.NORM_CDF(z FLOAT)
RETURNS FLOAT LANGUAGE SQL AS
$$
  SELECT CASE WHEN z >= 0 THEN 1 - phi ELSE phi END
  FROM (
    SELECT 0.3989422804014327 * EXP(-(ABS(z)*ABS(z))/2) *
           (k*(0.319381530 + k*(-0.356563782 + k*(1.781477937
            + k*(-1.821255978 + k*1.330274429))))) AS phi
    FROM (SELECT 1.0/(1.0 + 0.2316419*ABS(z)) AS k)
  )
$$;

CREATE OR REPLACE FUNCTION AUDIT.TWO_SIDED_P(stat FLOAT)
RETURNS FLOAT LANGUAGE SQL AS
$$ SELECT 2 * AUDIT.NORM_CDF(-ABS(stat)) $$;



