USE WAREHOUSE INTEL_WH;
USE DATABASE COMMODITY_INTEL;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FF
  TYPE='CSV' SKIP_HEADER=1 
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TRIM_SPACE=TRUE 
  NULL_IF=('','.','NA','N/A','null','NULL');

-- Header-parsing format so INFER_SCHEMA can read the WIDE EIA file by column name.

CREATE OR REPLACE FILE FORMAT RAW.CSV_FF_HEADER
  TYPE='CSV' PARSE_HEADER=TRUE 
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TRIM_SPACE=TRUE 
  NULL_IF=('','.','NA','N/A','null','NULL');

CREATE OR REPLACE STAGE RAW.LANDING FILE_FORMAT = RAW.CSV_FF;

COMMODITY_INTEL.RAW.LANDING

LIST @RAW.LANDING;